name: deploy to prod

on:
  push:
    branches:
      - main

jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: .
        target: server
        cache-from: type=gha
        cache-to: type=gha
        platforms: linux/amd64,linux/arm64
        push: true
        tags: whattheearl/jearl.io:latest

  publish-release-to-github:
    needs: [publish-to-dockerhub]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      MY_VAR: "this is my var"
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: echo myvar
      run: echo $MY_VAR

    - name: Publish Changelog and Version to Github
      uses: docker/build-push-action@v2
      with:
        build-args: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        context: .
        target: releaser
        cache-from: type=gha
        platforms: linux/amd64
        push: false


    # - name: setup aws cli
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-region: us-west-2
    #     role-to-assume: arn:aws:iam::682471220577:role/PUBLISH_TO_S3
    
    # - name: deploy to s3 (jearl.io)
    #   run: aws s3 sync ./out s3://jearl.io
