name: deploy to prod

on:
  push:
    branches:
      - main

jobs:
  run-lint-and-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jearl.io  
        
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: run lint and test
      run: |
        npm ci
        npm run lint
        npm run test --if-present

  publish-to-dockerhub:
    needs: [run-lint-and-tests]
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: whattheearl/jearl.io:latest

  publish-to-github:
    needs: [publish-to-dockerhub]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    
    steps:
    - name: Prepare Repo
      run: git fetch --unshallow --tags
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Release to Github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx auto shipit

    # - name: setup aws cli
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-region: us-west-2
    #     role-to-assume: arn:aws:iam::682471220577:role/PUBLISH_TO_S3
    
    # - name: deploy to s3 (jearl.io)
    #   run: aws s3 sync ./out s3://jearl.io
