name: deploy to prod

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jearl.io

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: lint
      run: |
        ls
        cd ..
        ls
        npm ci
        npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jearl.io  
        
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: test
      run: |
        npm ci
        npm run test --if-present

  deploy-to-prod:
    needs: [lint, test]
    name: deploy-to-prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    defaults:
      run:
        working-directory: ./jearl.io  

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: prepare repo
      # Fetch full git history and tags
      run: git fetch --unshallow --tags
    
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: build
      run: |
        npm ci
        npm run lint
        npm run build

    - name: setup aws cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::682471220577:role/PUBLISH_TO_S3
    
    - name: deploy to prod (jearl.io)
      run: aws s3 sync ./out s3://jearl.io

    - name: release to github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx auto shipit