name: lint test and build

on:

jobs:
  lint-test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Lint, Test and Build
      uses: docker/build-push-action@v2
      with:
        context: .
        target: builder
        cache-from: type=gha
        cache-to: type=gha
        platforms: linux/amd64
        push: false
