name: pr-verify

on: 
  pull_request:

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Lint
      uses: docker/build-push-action@v2
      with:
        context: .
        target: linter
        cache-from: type=gha
        cache-to: type=gha
        platforms: linux/amd64
        push: false

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Test
      uses: docker/build-push-action@v2
      with:
        context: .
        target: tester
        cache-from: type=gha
        cache-to: type=gha
        platforms: linux/amd64
        push: false

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: build
      uses: docker/build-push-action@v2
      with:
        context: .
        target: builder
        cache-from: type=gha
        cache-to: type=gha
        platforms: linux/amd64
        push: false

