name: Build and Release

on:
  push:
    branches:
      - main

jobs:          
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Build
      run: |
        npm ci
        npm run lint
        npm run build

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::682471220577:role/PUBLISH_TO_S3
        role-session-name: MySessionName
    
    - name: Publish to S3 bucket jearl.io
      run: |
        aws s3 sync ./out s3://jearl.io

    - name: Publish Release to Github
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git fetch --unshallow --tags
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        npm run release
